version: '3.1'

services:
  db:
    image: postgres:14-alpine
    restart: always
    container_name: postgres_eldo
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: 'user' 
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'eldo'
volumes:
  db-store: